QR_SAVE_DIR_PRE_FIX = '/var/depoma/qr/'
SAMPLE_SAVE_DIR_PRE_FIX = '/var/depoma/sample/'
MODEL_SAVE_DIR_PRE_FIX = '/var/depoma/model/'
DEFAULT_WEB_PROTOCOL = 'http://'
DEFAULT_SERVER_HOST = '123.207.136.243'
DEFAULT_SERVER_PORT = '8080'
DEFAULT_SERVER_RESOURCES_PORT = '80'
COLON = ':'


def server_prefix():
    return DEFAULT_WEB_PROTOCOL + DEFAULT_SERVER_HOST + COLON + DEFAULT_SERVER_PORT


def server_resources_prefix():
    return DEFAULT_WEB_PROTOCOL + DEFAULT_SERVER_HOST + COLON + DEFAULT_SERVER_RESOURCES_PORT
