version: "3"
services:
  jenkins:
    image: jenkinsci/blueocean:lts
    deploy:
    replicas: 1
        resources:
          limits:
            cpus: "0.5"
             memory: 500M
        restart_policy:
          condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes:
      - "/home/icusin/jenkins/jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME:/home"
    user: root
networks:
  webnet: