export const TOGGLE_MENU_STATUS = 'TOGGLE_MENU_STATUS';

export const BOTTOM_NAV_CHECKED_INDEX_CHANGE = 'BOTTOM_NAV_CHECKED_INDEX_CHANGE';

export const WECHAT_LOGIN_STATE_CHANGE = 'WECHAT_LOGIN_STATE_CHANGE';

export const LOAD_WECHAT_LOGIN_PAYLOAD = 'LOAD_WECHAT_LOGIN_PAYLOAD';
export const LOAD_WECHAT_LOGIN_PAYLOAD_SUCCESS = 'LOAD_WECHAT_LOGIN_PAYLOAD_SUCCESS';
export const LOAD_WECHAT_LOGIN_PAYLOAD_FAIL = 'LOAD_WECHAT_LOGIN_PAYLOAD_FAIL';

export const LOAD_WECHAT_LOGIN_STATE = 'LOAD_WECHAT_LOGIN_STATE';
export const LOAD_WECHAT_LOGIN_STATE_SUCCESS = 'LOAD_WECHAT_LOGIN_STATE_SUCCESS';
export const LOAD_WECHAT_LOGIN_STATE_FAIL = 'LOAD_WECHAT_LOGIN_STATE_FAIL';

export const LOAD_WECHAT_INFO = 'LOAD_WECHAT_INFO';
export const LOAD_WECHAT_INFO_SUCCESS = 'LOAD_WECHAT_INFO_SUCCESS';
export const LOAD_WECHAT_INFO_FAIL = 'LOAD_WECHAT_INFO_FAIL';

export const LOAD_CHAT_RECORDS = 'LOAD_CHAT_RECORDS';
export const LOAD_CHAT_RECORDS_SUCCESS = 'LOAD_CHAT_RECORDS_SUCCESS';
export const LOAD_CHAT_RECORDS_FAIL = 'LOAD_CHAT_RECORDS_FAIL';