export const TOGGLE_MENU_STATUS = 'TOGGLE_MENU_STATUS';

export const BOTTOM_NAV_CHECKED_INDEX_CHANGE = 'BOTTOM_NAV_CHECKED_INDEX_CHANGE';

export const WECHAT_LOGIN_STATE_CHANGE = 'WECHAT_LOGIN_STATE_CHANGE';

export const LOAD_WECHAT_GRANT_QR_SUCCESSFULLY = 'LOAD_WECHAT_GRANT_QR_SUCCESSFULLY';